def main():

# (a)
    print("(A): ", "Hello, world!", sep="")
# (b)
    print("(B): ", "Hello", "world!", sep="")
# (c)
    print("(C): ", 3, sep="")
# (d)
    print("(D): ", 3.0, sep="")
# (e)
    print("(E): ", 2+3, sep="")
# (f)
    print("(F): ", 2.0 + 3.0, sep="")
# (g)
    print("(G): ", "2" + "3", sep="")
# (h)
    print("(H): ", "2 + 3 =", 2 + 3, sep="")
# (i)
    print("(I): ", 2 * 3, sep="")
# (j)
    print("(J): ", 2 ** 3, sep="")
# (k)
    print("(K): ", 2 / 3, sep="")

main()